name: Build mimacro (Linux)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 24
          
      - name: Install X11 dev libraries
        run: sudo apt-get update && sudo apt-get install -y libx11-dev libxtst-dev libpng++-dev build-essential libudev-dev

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - run: npx electron-builder --linux --publish always
        working-directory: ./electron
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}